config/routes.rb
Rails.application.routes.draw do
  resources :places
  # get 'welcome/index'
  root "welcome#index"
  get 'all_places' => 'welcome#place_index', as: 'home_places'
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  # resources :comments
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users
  resources :events do
    resources :comments, :except => [:index]
    resources :attendances
  end
  put 'events/:id/public' => 'events#public_event', as: 'public_event'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :comments
    has_many :users, through: :attendances
    has_many :taggings
    has_many :tags, through: :taggings
    has_many_attached :pictures
    scope :by_hidden_status, -> {where hidden_status: false }
    validates :start, presence: true, date: { after: Proc.new { Date.today + 2 }, message: "must be at least #{(Date.today + 4).strftime("%H:%M %Y/%m/%d").to_s}" }, on: :create
    validates :end, presence: true, date: { after:  :start}
    belongs_to :place

    def all_tags=(names)
        self.tags = names.split(",").map do |name|
            Tag.where(name: name.strip).first_or_create!
        end
    end
    
    def all_tags
        self.tags.map(&:name).join(", ")
    end

    def self.tagged_with(name)
        Tag.find_by_name!(name).events
    end
end

app/controllers/events_controller.rb
require 'open_weather'

class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :public_event]
  before_action :authenticate_user!, except: [:show]
  after_action :verify_authorized

  extend EventsHelper

  # GET /events
  # GET /events.json
  def index
    authorize Event
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    authorize @event
    @comment = Comment.new
    @comments = @event.comments
    @attendance = @event.attendances.find_by(user_id: current_user.id) if user_signed_in? 
    options = { units: "metric", APPID: Rails.application.credentials.open_weather_map_api_key}
    options[:cnt] = 2
    @weathers = OpenWeather::ForecastDaily.geocode(@event.place.latitude, @event.place.longitude, options)
  end

  # GET /events/new
  def new
    authorize Event
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    authorize @event
  end

  # POST /events
  # POST /events.json
  def create
    authorize Event
    @event = Event.new(event_params)
    @event.hidden_status = true

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    authorize Event
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def public_event
    authorize Event
    @event.update_attribute(:hidden_status, false)
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully updated.' }
      format.json { render :show, status: :ok, location: @event }
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    authorize @event
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params[:event][:start] = params[:event][:start].to_datetime
      params[:event][:end] = params[:event][:end].to_datetime
      params.require(:event).permit(:name, :description, :place_id, :start, :end, :age_filter, :all_tags, pictures: [])
    end
end

app/helpers/events_helper.rb
module EventsHelper
    def time_format(time)
        time.strftime("%H:%M %Y/%m/%d")
    end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, class: "form-horizontal") do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_field :name, :class => "form-control", required: true %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label "Tags", :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_field :all_tags, placeholder: "Tags separated with comma", :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_area :description, :class => "form-control", required: true %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :place, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%# <%= form.number_field :place_id, :class => "form-control" %> 
      <%= select("event", "place_id", Place.all.collect {|place| [ place.name, place.id ] }, { include_blank: true }, class: "form-control") %>
    </div>
  </div>
  
  <div class="form-group row">
    <%= form.label :age, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.number_field :age_filter, :class => "form-control", :min => 0, required: true %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :start, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_field :start, :id => "start", :class => "form-control", :autocomplete => "off", required: true %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :end, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_field :end, :id => "end", :class => "form-control", :autocomplete => "off", required: true %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :pictures, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.file_field :pictures, :multiple => true %>
    </div>
  </div>

  <div class="form-group"> 
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit :class => "btn btn-primary" %>
    </div>
  </div>

<script>
  $('#start').datetimepicker({ 
    footer: true,
    format: 'HH:MM yyyy-mm-dd',
    datepicker: { 
      minDate: function() {
        var date = new Date();
        return new Date(date.getFullYear(), date.getMonth(), date.getDate());
      }
    }
  });
  $('#end').datetimepicker({ 
    footer: true,
    format: 'HH:MM yyyy-mm-dd',
    datepicker: { 
      minDate: function() {
        var date = new Date();
        return new Date(date.getFullYear(), date.getMonth(), date.getDate());
      }
    }
  });
</script>
<% end %>

app/views/events/edit.html.erb
<div class="row">
    <%= render('layouts/adminsidenav') %>
    <div class="col-md-7">
        <h1>Editing Event</h1>
        <%= render 'form', event: @event %>

    <%= link_to 'Show', @event %> |
    <%= link_to 'Back', events_path %>
    
    </div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <%= render('layouts/adminsidenav') %>
    <div class="col-md-9">
      <h1>Events</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Place</th>
            <th>Start</th>
            <th>End</th>
            <th colspan="5">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.place.name %></td>
              <td><%= time_format(event.start) %></td>
              <td><%= time_format(event.end) %></td>
              <td><%= link_to 'Show', event, class: "btn btn-info" %></td>
              <td><%= link_to 'Edit', edit_event_path(event), class: "btn btn-warning" %></td>
              <% if event.hidden_status== true %>
                <td><%= link_to 'Public Event', public_event_path(event), method: :put, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
              <% else %>
                <td><%= link_to 'Event has been public', public_event_path(event), class: "btn btn-disabled" %></td>
              <% end %>
              <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>

      <%= link_to 'New Event', new_event_path, class: "btn btn-success" %>
    </div>
</div>

app/views/events/new.html.erb
<div class="row">
    <%= render('layouts/adminsidenav') %>
    <div class="col-md-7">
        <h1>New Event</h1>
        <%= render 'form', event: @event %>
        <%= link_to 'Back', events_path %>
    </div>
</div>

app/views/events/show.html.erb
<div class="container mt-5">  
  <div class="row">
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-6">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active image-slide-size">
                <%= image_tag(@event.pictures.first, :alt => "Event picture", :class => "event-pictures") if @event.pictures.attached? %>
              </div>
              <% @event.pictures.drop(1).each do |picture| %>
                <div class="carousel-item image-slide-size">
                  <%= image_tag(picture, :alt => "Event picture", :class => "event-pictures") if @event.pictures.attached? %>
                </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
        <div class="col-md-6">
          <p><%= @event.name %></p>

          <p>
            <strong>Tags:</strong>
            <%=raw tag_links(@event.all_tags)%>
          </p>

          <p>
            <strong>Place:</strong>
            <%= link_to @event.place.name, place_path(@event.place) %>
          </p>

          <p>
            <strong>Start:</strong>
            <%= @event.start %>
          </p>

          <p>
            <strong>End:</strong>
            <%= @event.end %>
          </p>
        </div>
      </div>

      <p>
        <strong>Description:</strong>
        <%= @event.description %>
      </p>

      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <%= link_to 'Edit', edit_event_path(@event), :class => "btn btn-primary" %> 
          <%= link_to 'Back', "javascript: history.go(-1)", :class => "btn btn-secondary" %>
        <% else %>
          <% if @event.user_ids.include?(current_user.id) %>
            <p>You have signed up for <span id="current_attendance"><%= @attendance.accompanied_number %></span> people.</p>
            <%= link_to "Edit Joining", edit_event_attendance_path(@event, @attendance), :remote => true,
              :class => "btn btn-success", 'data-toggle' => 'modal', 'data-target' => "#attend-form" %>
          <% else %>
            <p id="join_event">Do you want to register for the event?</p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#attend-form" id="create-join">
              Join
            </button>
          <% end %>
          <div class="modal fade" id="attend-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <%= render 'attendances/form' %> 
            </div>
          </div>

          <%= link_to 'Back', "javascript: history.go(-1)", :class => "btn btn-secondary" %>
          <div class="comment-form mt-2">
            <%= render partial: "comments/form", locals: { event: @event, comment: @comment } %>
          </div>

        <% end %>
      <% else %>
        <p>Sign in to comment</p>
      <% end %>
      <div class="comments-list mt-2">
        <%= render partial: "comments/index",  collection: @event.comments, as: "comment" %>
      </div>
    </div>
    <div class="col-md-3">
      <%= render('layouts/advertisement') %>

      <h5 class="mt-3">Today and tomorrow's weather</h5>
      <table class="table table-bordered">
        <thead>
          <tr class="text-center">
            <% @weathers["list"].each do |weather| %>
                <th><%= place_datetime_format(weather["dt"]) %></th> <%# strptime ở đây %>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @weathers["list"].each do |weather| %>
              <td class="text-center">
                <p>
                  <%= image_tag 'http://openweathermap.org/img/w/'+weather["weather"][0]["icon"]+'.png', alt: "Weather" %>
                </p>
                <p><%= weather["weather"][0]["main"] %></p>
                <p><%= weather["temp"]["day"] %> &#8451</p>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>