config/routes.rb
Rails.application.routes.draw do
  resources :places
  # get 'welcome/index'
  root "welcome#index"
  get 'all_places' => 'welcome#place_index', as: 'home_places'
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  # resources :comments
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users
  resources :events do
    resources :comments, :except => [:index]
    resources :attendances
  end
  put 'events/:id/public' => 'events#public_event', as: 'public_event'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
    has_one_attached :picture
    has_many :events
end

app/controllers/places_controller.rb
require 'open_weather'

class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  rescue_from Pundit::NotAuthorizedError, with: :user_place_not_authorized
  before_action :authenticate_user!, except: [:show]
  after_action :verify_authorized
  
  extend PlacesHelper

  # GET /places
  # GET /places.json
  def index
    authorize Place
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    authorize @place
    options = { units: "metric", APPID: Rails.application.credentials.open_weather_map_api_key}
    options[:cnt] = 7
    @weathers = OpenWeather::ForecastDaily.geocode(@place.latitude, @place.longitude, options)
    # byebug
  end

  # GET /places/new
  def new
    authorize Place
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
    authorize @place
  end

  # POST /places
  # POST /places.json
  def create
    authorize Place
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    authorize Place
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    authorize @place
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :picture, :latitude, :longitude)
    end

    def user_place_not_authorized
        redirect_to (home_places_path)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
    def place_datetime_format(time)
        Time.at(time).strftime("%d %B")
    end
end

app/views/places/_form.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", initMap2);
    </script>
<% end %>

<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.text_area :description, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :picture, :class => "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= form.file_field :picture %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9">
      <div id="map2"></div>
    </div>

    <div class="col-md-3">
      <div class="form-group row">
        <%= form.label "Lat:", :class => "control-label col-sm-3" %>
        <div class="col-sm-8">
          <%= form.text_field :latitude, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label "Long:", :class => "control-label col-sm-3" %>
        <div class="col-sm-8">
          <%= form.text_field :longitude, :class => "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group mt-2"> 
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/places/edit.html.erb
<div class="row">
    <%= render('layouts/adminsidenav') %>
    <div class="col-md-7">
        <h1>Editing Place</h1>

        <%= render 'form', place: @place %>

        <%= link_to 'Show', @place, class: "btn btn-info" %> 
        <%= link_to 'Back', places_path, class: "btn btn-link" %>
    </div>
</div>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <%= render('layouts/adminsidenav') %>
    <div class="col-md-9">
      <h1>Events</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @places.each do |place| %>
            <tr>
              <td><%= place.name %></td>
              <td><%= place.latitude %></td>
              <td><%= place.longitude %></td>
              <td><%= link_to 'Show', place, class: "btn btn-info" %></td>
              <td><%= link_to 'Edit', edit_place_path(place), class: "btn btn-warning" %></td>
              <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Place', new_place_path, class: "btn btn-success"  %>
    </div>
</div>

app/views/places/new.html.erb
<div class="row">
    <%= render('layouts/adminsidenav') %>
    <div class="col-md-7">
        <h1>New Place</h1>

        <%= render 'form', place: @place %>

        <%= link_to 'Back', places_path, class: "btn btn-link" %>
    </div>
</div>

app/views/places/show.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(<%=@place.latitude%>, <%=@place.longitude%>)
    });
  </script>
<% end %>

<p id="notice"><%= notice %></p>

<div class="row">    
    <% if user_signed_in? && current_user.admin? %>
      <%= render('layouts/adminsidenav') %>
    <% else %>
      <%= render('layouts/sidenav') %>
    <% end %>

    <div class="col-md-7">
      <h1>
        <%= @place.name %>
      </h1>

      <div class="row">
        <div class="col-md-9 place-image-holder">
          <%= image_tag(@place.picture, :alt => "Place picture", :class => "place-picture") if @place.picture.attached? %>
        </div>

        <div class="col-md-3">
          <div id="map"></div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-9 offset-md-2">
        <p>
          <strong>Description:</strong>
          <%= @place.description %>
        </p>

        <h4>Weather this week:</h4>
        <table class="table table-bordered">
          <thead>
            <tr class="text-center">
              <% @weathers["list"].each do |weather| %>
                  <th><%= place_datetime_format(weather["dt"]) %></th> <%# strptime ở đây %>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% @weathers["list"].each do |weather| %>
                <td class="text-center">
                  <p>
                    <%= image_tag 'http://openweathermap.org/img/w/'+weather["weather"][0]["icon"]+'.png', alt: "Weather" %>
                  </p>
                  <p><%= weather["weather"][0]["main"] %></p>
                  <p><%= weather["temp"]["day"] %> &#8451</p>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>

        <% if user_signed_in? && current_user.admin? %>
          <%= link_to 'Edit', edit_place_path(@place), class: "btn btn-warning" %>
        <% end %>
        <%= link_to 'Back', places_path, class: "btn btn-link" %>
      </div>
    </div>
</div>