config/routes.rb
Rails.application.routes.draw do
  resources :places
  # get 'welcome/index'
  root "welcome#index"
  get 'all_places' => 'welcome#place_index', as: 'home_places'
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  # resources :comments
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users
  resources :events do
    resources :comments, :except => [:index]
    resources :attendances
  end
  put 'events/:id/public' => 'events#public_event', as: 'public_event'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_adminsidenav.html.erb
<div class="col-md-2">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <%= link_to 'Manage Places', places_path, method: :get, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Manage Events', events_path, method: :get, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Manage Admins', users_path, method: :get, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">View analytics</a>
    </li>
  </ul>
</div>

app/views/layouts/_advertisement.html.erb
      <div class="card">
        <div class="card-header">
          Advertisement
        </div>
        <%= link_to image_tag("LuPat.jpg", :alt => "Advertisement", :width => "100%"), "https://www.toei.co.jp/tv/lupin-vs-pat/", :target => "_blank"%>
      </div>

app/views/layouts/_footer.html.erb
<footer class="container-fluid">
    Project by BlazingRockStorm &copy
</footer>

app/views/layouts/_navigation.html.erb
<header>
    <nav class="navbar navbar-expand-md navbar-light bg-faded">
      <%= link_to "Let's go", root_path, method: :get, class: "navbar-brand" %>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline mr-auto">
            <input class="form-control mr-sm-2" type="search" placeholder="Search">
            <button class="btn btn-light my-2 my-sm-0" type="submit">Submit</button>
        </form>
        <ul class="navbar-nav">
          <!-- đã đăng nhập -->
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="javascript:void(0)" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <p style="display:inline"><%= current_user.name %></p> 
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
              <% if current_user.admin? %>
                <%= link_to 'Manage Events', events_path, method: :get, class: "dropdown-item" %>
                <%= link_to 'Manage Admins', users_path, method: :get, class: "dropdown-item" %>
              <% else %>
                <%= link_to 'Settings', edit_user_path(current_user), class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
          <!-- kết thúc phần đã đăng nhập -->
          <% else %>
          <!-- chưa đăng nhập -->
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, method: :get, class: "nav-link" %>
          </li>
          <!-- kết thúc phần chưa đăng nhập -->
          <% end %>
        </ul>
      </div>
    </nav>
</header>

app/views/layouts/_sidenav.html.erb
<div class="col-md-2">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <%= link_to 'Events', root_path, method: :get, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Places', home_places_path, method: :get, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Top</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Q&A</a>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Go</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.google_maps_api_key %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>

    <div class="body container-fluid mb-5">
      <%= yield %>
    </div>

    <%= render 'layouts/footer'%>
  </body>
</html>